export interface JobApplication {
    id?: number; // Optional if it's generated by the server
    personalInfo: {
      name: string;
      email: string;
      phone: string;
    };
    education: {
      degree: string;
      university: string;
      major: string;
      graduationYear: string;
      gpa: string;
    };
    experience: {
      yearsExperience: string;
      jobTitle: string;
    };
  }
  